"""Add new warehouse model

Revision ID: 0423f7f0259e
Revises: 8709a7193a4d
Create Date: 2026-08-22 15:16:20.018356

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0423f7f0259e"
down_revision: Union[str, Sequence[str], None] = "8709a7193a4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chambers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("code", sa.String(length=8), nullable=False),
        sa.Column(
            "category",
            sa.Enum("FROZEN", "CHILLED", "AMBIENT", name="chambercategory"),
            nullable=False,
        ),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "MAINTENANCE", "INACTIVE", name="chamberstatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chambers_code"), "chambers", ["code"], unique=True)
    op.create_index(op.f("ix_chambers_id"), "chambers", ["id"], unique=False)
    op.create_index(op.f("ix_chambers_name"), "chambers", ["name"], unique=True)
    op.create_table(
        "racks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("chamber_id", sa.UUID(), nullable=False),
        sa.Column("rack_number", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "FULL", "MAINTENANCE", "INACTIVE", name="rackstatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["chamber_id"], ["chambers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chamber_id", "rack_number", name="unique_chamber_rack"),
    )
    op.create_index(op.f("ix_racks_id"), "racks", ["id"], unique=False)
    op.create_index(
        op.f("ix_racks_rack_number"), "racks", ["rack_number"], unique=False
    )
    op.create_table(
        "slots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("rack_id", sa.UUID(), nullable=False),
        sa.Column("slot_number", sa.String(length=50), nullable=False),
        sa.Column("is_occupied", sa.Boolean(), nullable=False),
        sa.Column("allocated_client_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["allocated_client_id"], ["clients.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["rack_id"], ["racks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rack_id", "slot_number", name="unique_rack_slot"),
    )
    op.create_index(op.f("ix_slots_id"), "slots", ["id"], unique=False)
    op.create_index(
        op.f("ix_slots_slot_number"), "slots", ["slot_number"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_slots_slot_number"), table_name="slots")
    op.drop_index(op.f("ix_slots_id"), table_name="slots")
    op.drop_table("slots")
    op.drop_index(op.f("ix_racks_rack_number"), table_name="racks")
    op.drop_index(op.f("ix_racks_id"), table_name="racks")
    op.drop_table("racks")
    op.drop_index(op.f("ix_chambers_name"), table_name="chambers")
    op.drop_index(op.f("ix_chambers_id"), table_name="chambers")
    op.drop_index(op.f("ix_chambers_code"), table_name="chambers")
    op.drop_table("chambers")
    # ### end Alembic commands ###
