"""Client table updates

Revision ID: 0ea8b6b1f133
Revises: 21adda0cf836
Create Date: 2026-07-29 22:58:42.907396

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0ea8b6b1f133"
down_revision: Union[str, Sequence[str], None] = "21adda0cf836"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clients", sa.Column("name", sa.String(length=255), nullable=False))
    op.add_column(
        "clients", sa.Column("phone_number", sa.String(length=20), nullable=False)
    )
    op.add_column("clients", sa.Column("pin_code", sa.Integer(), nullable=False))
    op.add_column("clients", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.drop_column("clients", "company_name")
    op.drop_column("clients", "phone")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clients",
        sa.Column("phone", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    )
    op.add_column(
        "clients",
        sa.Column(
            "company_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("clients", "is_active")
    op.drop_column("clients", "pin_code")
    op.drop_column("clients", "phone_number")
    op.drop_column("clients", "name")
    # ### end Alembic commands ###
