"""add pick_lists and pick_records tables

Revision ID: 394e1cdd2a87
Revises: a8e742edfa43
Create Date: 2026-09-06 00:47:44.575803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '394e1cdd2a87'
down_revision: Union[str, Sequence[str], None] = 'a8e742edfa43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pick_lists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('outbound_order_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('total_lines', sa.Integer(), nullable=False),
    sa.Column('total_quantity', sa.Float(), nullable=False),
    sa.Column('total_weight_mt', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outbound_order_id'], ['outbound_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pick_lists_client_id'), 'pick_lists', ['client_id'], unique=False)
    op.create_index(op.f('ix_pick_lists_id'), 'pick_lists', ['id'], unique=False)
    op.create_index(op.f('ix_pick_lists_outbound_order_id'), 'pick_lists', ['outbound_order_id'], unique=True)
    op.create_table('pick_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pick_list_id', sa.UUID(), nullable=False),
    sa.Column('pallet_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('picked', sa.Boolean(), nullable=False),
    sa.Column('picked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pallet_id'], ['pallets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pick_list_id'], ['pick_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pick_records_id'), 'pick_records', ['id'], unique=False)
    op.create_index(op.f('ix_pick_records_pallet_id'), 'pick_records', ['pallet_id'], unique=False)
    op.create_index(op.f('ix_pick_records_pick_list_id'), 'pick_records', ['pick_list_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pick_records_pick_list_id'), table_name='pick_records')
    op.drop_index(op.f('ix_pick_records_pallet_id'), table_name='pick_records')
    op.drop_index(op.f('ix_pick_records_id'), table_name='pick_records')
    op.drop_table('pick_records')
    op.drop_index(op.f('ix_pick_lists_outbound_order_id'), table_name='pick_lists')
    op.drop_index(op.f('ix_pick_lists_id'), table_name='pick_lists')
    op.drop_index(op.f('ix_pick_lists_client_id'), table_name='pick_lists')
    op.drop_table('pick_lists')
    # ### end Alembic commands ###
