"""add order item, quantity and unit to pallets

Revision ID: 4eacfe82df6b
Revises: 8a48916815b5
Create Date: 2026-09-04 16:12:43.227963

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4eacfe82df6b"
down_revision: Union[str, Sequence[str], None] = "8a48916815b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pallets", sa.Column("order_item_id", sa.UUID(), nullable=True))
    op.add_column("pallets", sa.Column("quantity", sa.Float(), nullable=False))
    op.add_column(
        "pallets",
        sa.Column(
            "unit", sa.Enum("KG", "LB", "G", "OC", name="unitcategory"), nullable=True
        ),
    )
    op.create_index(
        op.f("ix_pallets_order_item_id"), "pallets", ["order_item_id"], unique=False
    )
    op.create_foreign_key(
        None, "pallets", "order_items", ["order_item_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "pallets", type_="foreignkey")
    op.drop_index(op.f("ix_pallets_order_item_id"), table_name="pallets")
    op.drop_column("pallets", "unit")
    op.drop_column("pallets", "quantity")
    op.drop_column("pallets", "order_item_id")
    # ### end Alembic commands ###
