"""changed from phone to phone_number in User model

Revision ID: 8709a7193a4d
Revises: 0ea8b6b1f133
Create Date: 2026-07-30 22:23:56.121456

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8709a7193a4d"
down_revision: Union[str, Sequence[str], None] = "0ea8b6b1f133"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("phone_number", sa.String(length=20), nullable=True)
    )
    op.drop_column("users", "phone")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("phone", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    )
    op.drop_column("users", "phone_number")
    # ### end Alembic commands ###
