"""renamed the inbound order item model

Revision ID: a7ee3bf2a3c4
Revises: 22e6a420fc6c
Create Date: 2026-09-04 19:41:52.899165

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7ee3bf2a3c4"
down_revision: Union[str, Sequence[str], None] = "22e6a420fc6c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Define enum values as constants for better maintainability
CHAMBER_CATEGORIES = ["FROZEN", "CHILLED", "AMBIENT"]
ORDER_STATUSES = [
    "SUBMITTED",
    "APPROVED",
    "REJECTED",
    "IN_TRANSIT",
    "ARRIVED",
    "PROCESSING",
    "STORED",
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    chamber_enum = postgresql.ENUM(*CHAMBER_CATEGORIES, name="chambercategory")
    chamber_enum.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "inbound_order_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("product_name", sa.String(length=255), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column(
            "temperature_category",
            postgresql.ENUM(
                *CHAMBER_CATEGORIES, name="chambercategory", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("batch_number", sa.String(length=255), nullable=False),
        sa.Column("expiry_date", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"], ["inbound_orders.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inbound_order_items_id"), "inbound_order_items", ["id"], unique=False
    )
    op.drop_index(op.f("ix_order_items_id"), table_name="order_items")
    op.drop_constraint(
        op.f("pallets_order_item_id_fkey"), "pallets", type_="foreignkey"
    )
    op.drop_table("order_items")
    op.create_foreign_key(
        None,
        "pallets",
        "inbound_order_items",
        ["order_item_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "pallets", type_="foreignkey")
    op.create_foreign_key(
        op.f("pallets_order_item_id_fkey"),
        "pallets",
        "order_items",
        ["order_item_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_table(
        "order_items",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("order_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "product_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "quantity",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "temperature_category",
            postgresql.ENUM("FROZEN", "CHILLED", "AMBIENT", name="chambercategory"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "batch_number", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "expiry_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["inbound_orders.id"],
            name=op.f("order_items_order_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("order_items_pkey")),
    )
    op.create_index(op.f("ix_order_items_id"), "order_items", ["id"], unique=False)
    op.drop_index(op.f("ix_inbound_order_items_id"), table_name="inbound_order_items")
    op.drop_table("inbound_order_items")
    # ### end Alembic commands ###
