"""fix the relationship name issues of old OrderItem model name in inbound order and inventory model

Revision ID: a8e742edfa43
Revises: a7ee3bf2a3c4
Create Date: 2026-09-04 22:20:39.698321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8e742edfa43'
down_revision: Union[str, Sequence[str], None] = 'a7ee3bf2a3c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chambers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('category', sa.Enum('FROZEN', 'CHILLED', 'AMBIENT', name='chambercategory'), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'MAINTENANCE', 'INACTIVE', name='chamberstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chambers_code'), 'chambers', ['code'], unique=True)
    op.create_index(op.f('ix_chambers_id'), 'chambers', ['id'], unique=False)
    op.create_index(op.f('ix_chambers_name'), 'chambers', ['name'], unique=True)
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('pin_code', sa.Integer(), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=True)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_table('inbound_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_number', sa.String(length=255), nullable=False),
    sa.Column('total_quantity', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'APPROVED', 'REJECTED', 'IN_TRANSIT', 'ARRIVED', 'PROCESSING', 'STORED', name='orderrequeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_orders_id'), 'inbound_orders', ['id'], unique=False)
    op.create_table('outbound_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('total_quantity', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'DISPATCHED', name='outboundorderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbound_orders_client_id'), 'outbound_orders', ['client_id'], unique=False)
    op.create_index(op.f('ix_outbound_orders_id'), 'outbound_orders', ['id'], unique=False)
    op.create_table('racks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chamber_id', sa.UUID(), nullable=False),
    sa.Column('rack_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'FULL', 'MAINTENANCE', 'INACTIVE', name='rackstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chamber_id'], ['chambers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chamber_id', 'rack_number', name='unique_chamber_rack')
    )
    op.create_index(op.f('ix_racks_id'), 'racks', ['id'], unique=False)
    op.create_index(op.f('ix_racks_rack_number'), 'racks', ['rack_number'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', 'CLIENT', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('inbound_order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('temperature_category', sa.Enum('FROZEN', 'CHILLED', 'AMBIENT', name='chambercategory'), nullable=False),
    sa.Column('batch_number', sa.String(length=255), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['inbound_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_order_items_id'), 'inbound_order_items', ['id'], unique=False)
    op.create_table('outbound_order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('outbound_order_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['outbound_order_id'], ['outbound_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbound_order_items_id'), 'outbound_order_items', ['id'], unique=False)
    op.create_index(op.f('ix_outbound_order_items_outbound_order_id'), 'outbound_order_items', ['outbound_order_id'], unique=False)
    op.create_table('slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rack_id', sa.UUID(), nullable=False),
    sa.Column('slot_number', sa.String(length=50), nullable=False),
    sa.Column('is_occupied', sa.Boolean(), nullable=False),
    sa.Column('allocated_client_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['allocated_client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rack_id'], ['racks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rack_id', 'slot_number', name='unique_rack_slot')
    )
    op.create_index(op.f('ix_slots_id'), 'slots', ['id'], unique=False)
    op.create_index(op.f('ix_slots_slot_number'), 'slots', ['slot_number'], unique=False)
    op.create_table('pallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('order_item_id', sa.UUID(), nullable=True),
    sa.Column('pallet_code', sa.String(length=32), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('batch_code', sa.String(length=255), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature_category', sa.Enum('FROZEN', 'CHILLED', 'AMBIENT', name='chambercategory'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('is_partial', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ALLOCATED', 'STORED', name='palletstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['inbound_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_item_id'], ['inbound_order_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pallets_batch_code'), 'pallets', ['batch_code'], unique=False)
    op.create_index(op.f('ix_pallets_client_id'), 'pallets', ['client_id'], unique=False)
    op.create_index(op.f('ix_pallets_id'), 'pallets', ['id'], unique=False)
    op.create_index(op.f('ix_pallets_order_id'), 'pallets', ['order_id'], unique=False)
    op.create_index(op.f('ix_pallets_order_item_id'), 'pallets', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_pallets_pallet_code'), 'pallets', ['pallet_code'], unique=True)
    op.create_index(op.f('ix_pallets_product_name'), 'pallets', ['product_name'], unique=False)
    op.create_table('slot_allocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('pallet_id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('allocated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['inbound_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pallet_id'], ['pallets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slot_allocations_id'), 'slot_allocations', ['id'], unique=False)
    op.create_index(op.f('ix_slot_allocations_order_id'), 'slot_allocations', ['order_id'], unique=False)
    op.create_index(op.f('ix_slot_allocations_pallet_id'), 'slot_allocations', ['pallet_id'], unique=False)
    op.create_index(op.f('ix_slot_allocations_slot_id'), 'slot_allocations', ['slot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slot_allocations_slot_id'), table_name='slot_allocations')
    op.drop_index(op.f('ix_slot_allocations_pallet_id'), table_name='slot_allocations')
    op.drop_index(op.f('ix_slot_allocations_order_id'), table_name='slot_allocations')
    op.drop_index(op.f('ix_slot_allocations_id'), table_name='slot_allocations')
    op.drop_table('slot_allocations')
    op.drop_index(op.f('ix_pallets_product_name'), table_name='pallets')
    op.drop_index(op.f('ix_pallets_pallet_code'), table_name='pallets')
    op.drop_index(op.f('ix_pallets_order_item_id'), table_name='pallets')
    op.drop_index(op.f('ix_pallets_order_id'), table_name='pallets')
    op.drop_index(op.f('ix_pallets_id'), table_name='pallets')
    op.drop_index(op.f('ix_pallets_client_id'), table_name='pallets')
    op.drop_index(op.f('ix_pallets_batch_code'), table_name='pallets')
    op.drop_table('pallets')
    op.drop_index(op.f('ix_slots_slot_number'), table_name='slots')
    op.drop_index(op.f('ix_slots_id'), table_name='slots')
    op.drop_table('slots')
    op.drop_index(op.f('ix_outbound_order_items_outbound_order_id'), table_name='outbound_order_items')
    op.drop_index(op.f('ix_outbound_order_items_id'), table_name='outbound_order_items')
    op.drop_table('outbound_order_items')
    op.drop_index(op.f('ix_inbound_order_items_id'), table_name='inbound_order_items')
    op.drop_table('inbound_order_items')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_racks_rack_number'), table_name='racks')
    op.drop_index(op.f('ix_racks_id'), table_name='racks')
    op.drop_table('racks')
    op.drop_index(op.f('ix_outbound_orders_id'), table_name='outbound_orders')
    op.drop_index(op.f('ix_outbound_orders_client_id'), table_name='outbound_orders')
    op.drop_table('outbound_orders')
    op.drop_index(op.f('ix_inbound_orders_id'), table_name='inbound_orders')
    op.drop_table('inbound_orders')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_chambers_name'), table_name='chambers')
    op.drop_index(op.f('ix_chambers_id'), table_name='chambers')
    op.drop_index(op.f('ix_chambers_code'), table_name='chambers')
    op.drop_table('chambers')
    # ### end Alembic commands ###
