"""initial schema

Revision ID: c83a7e17b932
Revises: 
Create Date: 2026-09-27 20:54:17.499454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c83a7e17b932'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chambers',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('frozen', 'chilled', 'ambient')", name='valid_chamber_category'),
    sa.CheckConstraint("status IN ('active', 'maintenance', 'inactive')", name='valid_chamber_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chambers_code'), 'chambers', ['code'], unique=True)
    op.create_index(op.f('ix_chambers_name'), 'chambers', ['name'], unique=True)
    op.create_table('clients',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('pin_code', sa.Integer(), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=True)
    op.create_table('inbound_orders',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_number', sa.String(length=255), nullable=False),
    sa.Column('total_quantity', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'APPROVED', 'REJECTED', 'IN_TRANSIT', 'ARRIVED', 'PROCESSING', 'STORED', name='orderrequeststatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'VIEWED', 'PAID', name='invoicestatus', native_enum=False, length=20), nullable=False),
    sa.Column('billing_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('billing_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('cgst_rate', sa.Float(), nullable=True),
    sa.Column('cgst_amount', sa.Float(), nullable=True),
    sa.Column('sgst_rate', sa.Float(), nullable=True),
    sa.Column('sgst_amount', sa.Float(), nullable=True),
    sa.Column('igst_rate', sa.Float(), nullable=True),
    sa.Column('igst_amount', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_client_id'), 'invoices', ['client_id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_table('outbound_orders',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('total_quantity', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'DISPATCHED', name='outboundorderstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbound_orders_client_id'), 'outbound_orders', ['client_id'], unique=False)
    op.create_table('racks',
    sa.Column('chamber_id', sa.UUID(), nullable=False),
    sa.Column('rack_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'full', 'maintenance', 'inactive')", name='valid_rack_status'),
    sa.ForeignKeyConstraint(['chamber_id'], ['chambers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chamber_id', 'rack_number', name='unique_chamber_rack')
    )
    op.create_index(op.f('ix_racks_rack_number'), 'racks', ['rack_number'], unique=False)
    op.create_table('users',
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', 'CLIENT', name='userrole', native_enum=False, length=20), server_default=sa.text("'client'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(role = 'client' AND client_id IS NOT NULL) OR (role != 'client')", name='chk_user_client_role_has_client_id'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_client_id'), 'users', ['client_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('inbound_order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('temperature_category', sa.Enum('FROZEN', 'CHILLED', 'AMBIENT', name='chambercategory', native_enum=False, length=20), nullable=False),
    sa.Column('batch_number', sa.String(length=255), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['inbound_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_line_items',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('unit_rate_snapshot', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_line_items_invoice_id'), 'invoice_line_items', ['invoice_id'], unique=False)
    op.create_table('outbound_order_items',
    sa.Column('outbound_order_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['outbound_order_id'], ['outbound_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbound_order_items_outbound_order_id'), 'outbound_order_items', ['outbound_order_id'], unique=False)
    op.create_table('payments',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('method', sa.Enum('UPI', 'CARD', 'NETBANKING', 'WALLET', name='paymentmethod', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'AUTHORIZED', 'CAPTURED', 'FAILED', 'REFUNDED', name='paymentstatus', native_enum=False, length=20), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_signature', sa.String(length=128), nullable=True),
    sa.Column('receipt_number', sa.String(length=32), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_number')
    )
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_razorpay_order_id'), 'payments', ['razorpay_order_id'], unique=False)
    op.create_table('pick_lists',
    sa.Column('outbound_order_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('total_lines', sa.Integer(), nullable=False),
    sa.Column('total_quantity', sa.Float(), nullable=False),
    sa.Column('total_weight_mt', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outbound_order_id'], ['outbound_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pick_lists_client_id'), 'pick_lists', ['client_id'], unique=False)
    op.create_index(op.f('ix_pick_lists_outbound_order_id'), 'pick_lists', ['outbound_order_id'], unique=True)
    op.create_table('slots',
    sa.Column('rack_id', sa.UUID(), nullable=False),
    sa.Column('bay', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('location_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('allocated_client_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('available', 'reserved', 'occupied', 'maintenance')", name='valid_slot_status'),
    sa.ForeignKeyConstraint(['allocated_client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rack_id'], ['racks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rack_id', 'bay', 'level', 'depth', name='unique_rack_slot')
    )
    op.create_index(op.f('ix_slots_location_code'), 'slots', ['location_code'], unique=True)
    op.create_table('pallets',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('order_item_id', sa.UUID(), nullable=True),
    sa.Column('pallet_code', sa.String(length=32), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('batch_code', sa.String(length=255), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature_category', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('is_partial', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ALLOCATED', 'STORED', 'DISPATCHED', name='palletstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("temperature_category IN ('frozen', 'chilled', 'ambient')", name='valid_pallet_temperature_category'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['inbound_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_item_id'], ['inbound_order_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pallets_batch_code'), 'pallets', ['batch_code'], unique=False)
    op.create_index(op.f('ix_pallets_client_id'), 'pallets', ['client_id'], unique=False)
    op.create_index(op.f('ix_pallets_order_id'), 'pallets', ['order_id'], unique=False)
    op.create_index(op.f('ix_pallets_order_item_id'), 'pallets', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_pallets_pallet_code'), 'pallets', ['pallet_code'], unique=True)
    op.create_index(op.f('ix_pallets_product_name'), 'pallets', ['product_name'], unique=False)
    op.create_table('pick_records',
    sa.Column('pick_list_id', sa.UUID(), nullable=False),
    sa.Column('pallet_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('picked', sa.Boolean(), nullable=False),
    sa.Column('picked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['pallet_id'], ['pallets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pick_list_id'], ['pick_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pick_records_pallet_id'), 'pick_records', ['pallet_id'], unique=False)
    op.create_index(op.f('ix_pick_records_pick_list_id'), 'pick_records', ['pick_list_id'], unique=False)
    op.create_table('slot_allocations',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('pallet_id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('allocated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['inbound_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pallet_id'], ['pallets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slot_allocations_order_id'), 'slot_allocations', ['order_id'], unique=False)
    op.create_index(op.f('ix_slot_allocations_pallet_id'), 'slot_allocations', ['pallet_id'], unique=False)
    op.create_index(op.f('ix_slot_allocations_slot_id'), 'slot_allocations', ['slot_id'], unique=False)
    op.create_table('stock_levels',
    sa.Column('pallet_id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('weight_mt', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['pallet_id'], ['pallets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pallet_id', 'slot_id', name='uq_stock_level_pallet_slot')
    )
    op.create_index(op.f('ix_stock_levels_pallet_id'), 'stock_levels', ['pallet_id'], unique=False)
    op.create_index(op.f('ix_stock_levels_slot_id'), 'stock_levels', ['slot_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('pallet_id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.Enum('INBOUND', 'OUTBOUND', 'ADJUSTMENT', name='movementtype', native_enum=False, length=20), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('weight_mt', sa.Float(), nullable=False),
    sa.Column('reference_order_id', sa.UUID(), nullable=True),
    sa.Column('executed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['executed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pallet_id'], ['pallets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movements_movement_type'), 'stock_movements', ['movement_type'], unique=False)
    op.create_index(op.f('ix_stock_movements_pallet_id'), 'stock_movements', ['pallet_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_reference_order_id'), 'stock_movements', ['reference_order_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_slot_id'), 'stock_movements', ['slot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_movements_slot_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_reference_order_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_pallet_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_movement_type'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_stock_levels_slot_id'), table_name='stock_levels')
    op.drop_index(op.f('ix_stock_levels_pallet_id'), table_name='stock_levels')
    op.drop_table('stock_levels')
    op.drop_index(op.f('ix_slot_allocations_slot_id'), table_name='slot_allocations')
    op.drop_index(op.f('ix_slot_allocations_pallet_id'), table_name='slot_allocations')
    op.drop_index(op.f('ix_slot_allocations_order_id'), table_name='slot_allocations')
    op.drop_table('slot_allocations')
    op.drop_index(op.f('ix_pick_records_pick_list_id'), table_name='pick_records')
    op.drop_index(op.f('ix_pick_records_pallet_id'), table_name='pick_records')
    op.drop_table('pick_records')
    op.drop_index(op.f('ix_pallets_product_name'), table_name='pallets')
    op.drop_index(op.f('ix_pallets_pallet_code'), table_name='pallets')
    op.drop_index(op.f('ix_pallets_order_item_id'), table_name='pallets')
    op.drop_index(op.f('ix_pallets_order_id'), table_name='pallets')
    op.drop_index(op.f('ix_pallets_client_id'), table_name='pallets')
    op.drop_index(op.f('ix_pallets_batch_code'), table_name='pallets')
    op.drop_table('pallets')
    op.drop_index(op.f('ix_slots_location_code'), table_name='slots')
    op.drop_table('slots')
    op.drop_index(op.f('ix_pick_lists_outbound_order_id'), table_name='pick_lists')
    op.drop_index(op.f('ix_pick_lists_client_id'), table_name='pick_lists')
    op.drop_table('pick_lists')
    op.drop_index(op.f('ix_payments_razorpay_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_outbound_order_items_outbound_order_id'), table_name='outbound_order_items')
    op.drop_table('outbound_order_items')
    op.drop_index(op.f('ix_invoice_line_items_invoice_id'), table_name='invoice_line_items')
    op.drop_table('invoice_line_items')
    op.drop_table('inbound_order_items')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_client_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_racks_rack_number'), table_name='racks')
    op.drop_table('racks')
    op.drop_index(op.f('ix_outbound_orders_client_id'), table_name='outbound_orders')
    op.drop_table('outbound_orders')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_client_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_table('inbound_orders')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_chambers_name'), table_name='chambers')
    op.drop_index(op.f('ix_chambers_code'), table_name='chambers')
    op.drop_table('chambers')
    # ### end Alembic commands ###
